spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : ${DB_URL}
    username : ${DB_USERNAME}
    password : ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  main:
    allow-bean-definition-overriding: true

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      fail-on-empty-beans: false

  jwt:
    secretKey: ${JWT_SECRET}
    accessExp: ${ACCESS_EXP}
    refreshExp: ${REFRESH_EXP}
    header: ${HEADER}
    prefix: ${PREFIX}

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}

  messages:
    encoding: UTF-8

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

app:
  timezone: Asia/Seoul

discord:
  name: discord-feign-client
  webhook-url: ${discord.webhook-url}

logging:
  level:
    org.springframework.security: DEBUG
